/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterSuccessRouteImport } from './routes/registerSuccess'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PasswordForgottenRouteImport } from './routes/passwordForgotten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardUserRouteImport } from './routes/dashboardUser'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'

const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/registerSuccess',
  path: '/registerSuccess',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgottenRoute = PasswordForgottenRouteImport.update({
  id: '/passwordForgotten',
  path: '/passwordForgotten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/dashboardUser',
  path: '/dashboardUser',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboardUser': typeof DashboardUserRoute
  '/login': typeof LoginRoute
  '/passwordForgotten': typeof PasswordForgottenRoute
  '/register': typeof RegisterRoute
  '/registerSuccess': typeof RegisterSuccessRoute
  '/app': typeof AuthenticatedAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboardUser': typeof DashboardUserRoute
  '/login': typeof LoginRoute
  '/passwordForgotten': typeof PasswordForgottenRoute
  '/register': typeof RegisterRoute
  '/registerSuccess': typeof RegisterSuccessRoute
  '/app': typeof AuthenticatedAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboardUser': typeof DashboardUserRoute
  '/login': typeof LoginRoute
  '/passwordForgotten': typeof PasswordForgottenRoute
  '/register': typeof RegisterRoute
  '/registerSuccess': typeof RegisterSuccessRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboardUser'
    | '/login'
    | '/passwordForgotten'
    | '/register'
    | '/registerSuccess'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboardUser'
    | '/login'
    | '/passwordForgotten'
    | '/register'
    | '/registerSuccess'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/dashboardUser'
    | '/login'
    | '/passwordForgotten'
    | '/register'
    | '/registerSuccess'
    | '/_authenticated/app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DashboardUserRoute: typeof DashboardUserRoute
  LoginRoute: typeof LoginRoute
  PasswordForgottenRoute: typeof PasswordForgottenRoute
  RegisterRoute: typeof RegisterRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registerSuccess': {
      id: '/registerSuccess'
      path: '/registerSuccess'
      fullPath: '/registerSuccess'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwordForgotten': {
      id: '/passwordForgotten'
      path: '/passwordForgotten'
      fullPath: '/passwordForgotten'
      preLoaderRoute: typeof PasswordForgottenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardUser': {
      id: '/dashboardUser'
      path: '/dashboardUser'
      fullPath: '/dashboardUser'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  DashboardUserRoute: DashboardUserRoute,
  LoginRoute: LoginRoute,
  PasswordForgottenRoute: PasswordForgottenRoute,
  RegisterRoute: RegisterRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
