/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PasswordForgottenRouteImport } from './routes/password-forgotten'
import { Route as NotFoundRouteImport } from './routes/notFound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardHelperRouteImport } from './routes/dashboardHelper'
import { Route as DashboardUserIndexRouteImport } from './routes/dashboard-user/index'
import { Route as DashboardTeacherVeranstaltungenRouteImport } from './routes/dashboard-teacher/veranstaltungen'
import { Route as DashboardTeacherRegistrierungenRouteImport } from './routes/dashboard-teacher/registrierungen'
import { Route as DashboardUserAnmeldenEventIdRouteImport } from './routes/dashboard-user/anmelden/$eventId'
import { Route as DashboardUserBearbeitenInfostandRegistrationIDRouteImport } from './routes/dashboard-user/bearbeiten/infostand/$registrationID'
import { Route as DashboardTeacherDetailsRegistrationRegistrationIdRouteImport } from './routes/dashboard-teacher/details/registration/$registrationId'
import { Route as DashboardTeacherDetailsLectureRegistrationRouteImport } from './routes/dashboard-teacher/details/lecture/$registration'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgottenRoute = PasswordForgottenRouteImport.update({
  id: '/password-forgotten',
  path: '/password-forgotten',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/notFound',
  path: '/notFound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHelperRoute = DashboardHelperRouteImport.update({
  id: '/dashboardHelper',
  path: '/dashboardHelper',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/dashboard-user/',
  path: '/dashboard-user/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherVeranstaltungenRoute =
  DashboardTeacherVeranstaltungenRouteImport.update({
    id: '/dashboard-teacher/veranstaltungen',
    path: '/dashboard-teacher/veranstaltungen',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTeacherRegistrierungenRoute =
  DashboardTeacherRegistrierungenRouteImport.update({
    id: '/dashboard-teacher/registrierungen',
    path: '/dashboard-teacher/registrierungen',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUserAnmeldenEventIdRoute =
  DashboardUserAnmeldenEventIdRouteImport.update({
    id: '/dashboard-user/anmelden/$eventId',
    path: '/dashboard-user/anmelden/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUserBearbeitenInfostandRegistrationIDRoute =
  DashboardUserBearbeitenInfostandRegistrationIDRouteImport.update({
    id: '/dashboard-user/bearbeiten/infostand/$registrationID',
    path: '/dashboard-user/bearbeiten/infostand/$registrationID',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTeacherDetailsRegistrationRegistrationIdRoute =
  DashboardTeacherDetailsRegistrationRegistrationIdRouteImport.update({
    id: '/dashboard-teacher/details/registration/$registrationId',
    path: '/dashboard-teacher/details/registration/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTeacherDetailsLectureRegistrationRoute =
  DashboardTeacherDetailsLectureRegistrationRouteImport.update({
    id: '/dashboard-teacher/details/lecture/$registration',
    path: '/dashboard-teacher/details/lecture/$registration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboardHelper': typeof DashboardHelperRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/password-forgotten': typeof PasswordForgottenRoute
  '/register': typeof RegisterRoute
  '/dashboard-teacher/registrierungen': typeof DashboardTeacherRegistrierungenRoute
  '/dashboard-teacher/veranstaltungen': typeof DashboardTeacherVeranstaltungenRoute
  '/dashboard-user/': typeof DashboardUserIndexRoute
  '/dashboard-user/anmelden/$eventId': typeof DashboardUserAnmeldenEventIdRoute
  '/dashboard-teacher/details/lecture/$registration': typeof DashboardTeacherDetailsLectureRegistrationRoute
  '/dashboard-teacher/details/registration/$registrationId': typeof DashboardTeacherDetailsRegistrationRegistrationIdRoute
  '/dashboard-user/bearbeiten/infostand/$registrationID': typeof DashboardUserBearbeitenInfostandRegistrationIDRoute
}
export interface FileRoutesByTo {
  '/dashboardHelper': typeof DashboardHelperRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/password-forgotten': typeof PasswordForgottenRoute
  '/register': typeof RegisterRoute
  '/dashboard-teacher/registrierungen': typeof DashboardTeacherRegistrierungenRoute
  '/dashboard-teacher/veranstaltungen': typeof DashboardTeacherVeranstaltungenRoute
  '/dashboard-user': typeof DashboardUserIndexRoute
  '/dashboard-user/anmelden/$eventId': typeof DashboardUserAnmeldenEventIdRoute
  '/dashboard-teacher/details/lecture/$registration': typeof DashboardTeacherDetailsLectureRegistrationRoute
  '/dashboard-teacher/details/registration/$registrationId': typeof DashboardTeacherDetailsRegistrationRegistrationIdRoute
  '/dashboard-user/bearbeiten/infostand/$registrationID': typeof DashboardUserBearbeitenInfostandRegistrationIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboardHelper': typeof DashboardHelperRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/password-forgotten': typeof PasswordForgottenRoute
  '/register': typeof RegisterRoute
  '/dashboard-teacher/registrierungen': typeof DashboardTeacherRegistrierungenRoute
  '/dashboard-teacher/veranstaltungen': typeof DashboardTeacherVeranstaltungenRoute
  '/dashboard-user/': typeof DashboardUserIndexRoute
  '/dashboard-user/anmelden/$eventId': typeof DashboardUserAnmeldenEventIdRoute
  '/dashboard-teacher/details/lecture/$registration': typeof DashboardTeacherDetailsLectureRegistrationRoute
  '/dashboard-teacher/details/registration/$registrationId': typeof DashboardTeacherDetailsRegistrationRegistrationIdRoute
  '/dashboard-user/bearbeiten/infostand/$registrationID': typeof DashboardUserBearbeitenInfostandRegistrationIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboardHelper'
    | '/login'
    | '/notFound'
    | '/password-forgotten'
    | '/register'
    | '/dashboard-teacher/registrierungen'
    | '/dashboard-teacher/veranstaltungen'
    | '/dashboard-user/'
    | '/dashboard-user/anmelden/$eventId'
    | '/dashboard-teacher/details/lecture/$registration'
    | '/dashboard-teacher/details/registration/$registrationId'
    | '/dashboard-user/bearbeiten/infostand/$registrationID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboardHelper'
    | '/login'
    | '/notFound'
    | '/password-forgotten'
    | '/register'
    | '/dashboard-teacher/registrierungen'
    | '/dashboard-teacher/veranstaltungen'
    | '/dashboard-user'
    | '/dashboard-user/anmelden/$eventId'
    | '/dashboard-teacher/details/lecture/$registration'
    | '/dashboard-teacher/details/registration/$registrationId'
    | '/dashboard-user/bearbeiten/infostand/$registrationID'
  id:
    | '__root__'
    | '/dashboardHelper'
    | '/login'
    | '/notFound'
    | '/password-forgotten'
    | '/register'
    | '/dashboard-teacher/registrierungen'
    | '/dashboard-teacher/veranstaltungen'
    | '/dashboard-user/'
    | '/dashboard-user/anmelden/$eventId'
    | '/dashboard-teacher/details/lecture/$registration'
    | '/dashboard-teacher/details/registration/$registrationId'
    | '/dashboard-user/bearbeiten/infostand/$registrationID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardHelperRoute: typeof DashboardHelperRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  PasswordForgottenRoute: typeof PasswordForgottenRoute
  RegisterRoute: typeof RegisterRoute
  DashboardTeacherRegistrierungenRoute: typeof DashboardTeacherRegistrierungenRoute
  DashboardTeacherVeranstaltungenRoute: typeof DashboardTeacherVeranstaltungenRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
  DashboardUserAnmeldenEventIdRoute: typeof DashboardUserAnmeldenEventIdRoute
  DashboardTeacherDetailsLectureRegistrationRoute: typeof DashboardTeacherDetailsLectureRegistrationRoute
  DashboardTeacherDetailsRegistrationRegistrationIdRoute: typeof DashboardTeacherDetailsRegistrationRegistrationIdRoute
  DashboardUserBearbeitenInfostandRegistrationIDRoute: typeof DashboardUserBearbeitenInfostandRegistrationIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-forgotten': {
      id: '/password-forgotten'
      path: '/password-forgotten'
      fullPath: '/password-forgotten'
      preLoaderRoute: typeof PasswordForgottenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notFound': {
      id: '/notFound'
      path: '/notFound'
      fullPath: '/notFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardHelper': {
      id: '/dashboardHelper'
      path: '/dashboardHelper'
      fullPath: '/dashboardHelper'
      preLoaderRoute: typeof DashboardHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-user/': {
      id: '/dashboard-user/'
      path: '/dashboard-user'
      fullPath: '/dashboard-user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-teacher/veranstaltungen': {
      id: '/dashboard-teacher/veranstaltungen'
      path: '/dashboard-teacher/veranstaltungen'
      fullPath: '/dashboard-teacher/veranstaltungen'
      preLoaderRoute: typeof DashboardTeacherVeranstaltungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-teacher/registrierungen': {
      id: '/dashboard-teacher/registrierungen'
      path: '/dashboard-teacher/registrierungen'
      fullPath: '/dashboard-teacher/registrierungen'
      preLoaderRoute: typeof DashboardTeacherRegistrierungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-user/anmelden/$eventId': {
      id: '/dashboard-user/anmelden/$eventId'
      path: '/dashboard-user/anmelden/$eventId'
      fullPath: '/dashboard-user/anmelden/$eventId'
      preLoaderRoute: typeof DashboardUserAnmeldenEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-user/bearbeiten/infostand/$registrationID': {
      id: '/dashboard-user/bearbeiten/infostand/$registrationID'
      path: '/dashboard-user/bearbeiten/infostand/$registrationID'
      fullPath: '/dashboard-user/bearbeiten/infostand/$registrationID'
      preLoaderRoute: typeof DashboardUserBearbeitenInfostandRegistrationIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-teacher/details/registration/$registrationId': {
      id: '/dashboard-teacher/details/registration/$registrationId'
      path: '/dashboard-teacher/details/registration/$registrationId'
      fullPath: '/dashboard-teacher/details/registration/$registrationId'
      preLoaderRoute: typeof DashboardTeacherDetailsRegistrationRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-teacher/details/lecture/$registration': {
      id: '/dashboard-teacher/details/lecture/$registration'
      path: '/dashboard-teacher/details/lecture/$registration'
      fullPath: '/dashboard-teacher/details/lecture/$registration'
      preLoaderRoute: typeof DashboardTeacherDetailsLectureRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardHelperRoute: DashboardHelperRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  PasswordForgottenRoute: PasswordForgottenRoute,
  RegisterRoute: RegisterRoute,
  DashboardTeacherRegistrierungenRoute: DashboardTeacherRegistrierungenRoute,
  DashboardTeacherVeranstaltungenRoute: DashboardTeacherVeranstaltungenRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
  DashboardUserAnmeldenEventIdRoute: DashboardUserAnmeldenEventIdRoute,
  DashboardTeacherDetailsLectureRegistrationRoute:
    DashboardTeacherDetailsLectureRegistrationRoute,
  DashboardTeacherDetailsRegistrationRegistrationIdRoute:
    DashboardTeacherDetailsRegistrationRegistrationIdRoute,
  DashboardUserBearbeitenInfostandRegistrationIDRoute:
    DashboardUserBearbeitenInfostandRegistrationIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
